### LU Decomposition

In [6]:
import numpy as np
A = np.array([[1.19, 2.11, -100, 1], [14.2, -0.122, 12.2, -1], [0, 100, -99.9, 1], [15.3, 0.11, -13.1, -1]])
b = np.array([1.12, 3.44, 2.15, 4.16])
n = len(b)
L = np.identity(n)
print("A=\n", A)
print("\nb=", b)
for k in range(n):
    for i in range(k+1,n):
        m = A[i,k]/A[k,k]
        L[i,k]=m
        for j in range(k,n):
            A[i,j] = A[i,j] - m*A[k,j]
print("\nU=\n",A) 
print("\nL=\n",L) 

# Forward Substitution
y = np.zeros(n)
y[0] = b[0]
for i in range(1,n):
    sum = b[i]
    for j in range(0,i):
        sum = sum - L[i,j]*y[j]
    y[i] = sum
print('\n y =',y)

# Backward Substitution
x = np.zeros(n)
x[n-1] = y[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    sum = y[i]
    for j in range(i+1,n):
        sum = sum -A[i,j]*x[j]
    x[i] = sum/A[i,i]
print('\n x =',x)

A=
 [[   1.19     2.11  -100.       1.   ]
 [  14.2     -0.122   12.2     -1.   ]
 [   0.     100.     -99.9      1.   ]
 [  15.3      0.11   -13.1     -1.   ]]

b= [1.12 3.44 2.15 4.16]

U=
 [[ 1.19000000e+00  2.11000000e+00 -1.00000000e+02  1.00000000e+00]
 [ 0.00000000e+00 -2.53001513e+01  1.20547731e+03 -1.29327731e+01]
 [ 0.00000000e+00  0.00000000e+00  4.66480397e+03 -5.01173747e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.04328072e-01]]

L=
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.19327731e+01  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -3.95254554e+00  1.00000000e+00  0.00000000e+00]
 [ 1.28571429e+01  1.06792134e+00 -3.15997398e-03  1.00000000e+00]]

 y = [  1.12        -9.92470588 -37.07785196   0.24164015]

 x = [ 0.1768253   0.01269269 -0.02065405 -1.1826087 ]
